// host acceptance (R2): font lookup, text pagination and rendered pixels
// on a real CJK face, through the same core code the firmware runs:
// FontPack::load -> resolve / lookup -> layout::wrap with PackMeasure ->
// PageGlyphs::prepare -> PageGlyphs::draw per strip (strip harness)
//
// fixtures (tracked, OFL 1.1, see tools/fontpack/tests/fixtures/README.txt):
//   fixtures/iansui-sample.txt  Traditional Chinese paragraph with Latin,
//                               the kinsoku punctuation ，。、「」『』（）！？：；
//                               plus … and —, kana, and one Hangul syllable
//   fixtures/IANSUI24.PFP       the Iansui subset (printable ASCII, U+25A1
//                               and the sample's characters) at 24 px,
//                               generated by pulp-fontpack; its bytes are
//                               kept honest by pulp-fontpack's
//                               tracked_render_fixture_pack_is_reproducible
//
// oracle: expected values come from the subset recipe and the sample text
// (which characters exist), from clreq §6.1.1 (the punctuation sets below,
// restated here rather than taken from line_break) and from the page
// geometry; none is copied from running the code under test. pixel-exact
// goldens are not part of this file

mod common;

use common::TestReader;
use common::strip::{Frame, render_full};
use pulp_render::font_pack::FontPack;
use pulp_render::layout::{
    LineSpan, Markup, Measure, Style, WrapParams, WrapState, line_glyphs, next_page_offset, wrap,
    wrap_stream,
};
use pulp_render::page::{PackMeasure, PageGeometry, PageGlyphs};
use pulp_render::panel::Rotation;
use pulp_render::strip::StripBuffer;

const PX: u16 = 24;
const MAX_WIDTH: u32 = 240;
const MAX_LINES: usize = 6;
const LEFT: i32 = 20;
const TOP: i32 = 30;

// the sample contains no markup; any byte values would do
const MARKUP: Markup = Markup {
    marker: 0x01,
    img_ref: b'P',
    bold_on: b'B',
    bold_off: b'b',
    italic_on: b'I',
    italic_off: b'i',
    heading_on: b'H',
    heading_off: b'h',
    quote_on: b'Q',
    quote_off: b'q',
};

// clreq §6.1.1 (basic level), restricted to the marks the sample uses
const NO_LINE_START: &str = "，。、」』）！？：；";
const NO_LINE_END: &str = "「『（";
// clreq §6.1.2: a two-em dash or an ellipsis is never split
const NO_SPLIT_PAIRS: &str = "…—";

fn fixture(name: &str) -> Vec<u8> {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()))
}

fn sample() -> String {
    String::from_utf8(fixture("iansui-sample.txt")).unwrap()
}

fn is_hangul(ch: char) -> bool {
    matches!(ch as u32, 0x1100..=0x11FF | 0x3130..=0x318F | 0xAC00..=0xD7AF)
}

fn load() -> (TestReader, FontPack) {
    let mut r = TestReader::new(fixture("IANSUI24.PFP"));
    let pack = FontPack::load(&mut r, PX).expect("the tracked pack loads");
    r.reset_counts();
    (r, pack)
}

#[test]
fn lookup_finds_cjk_and_falls_back_for_hangul() {
    let (mut r, pack) = load();
    let text = sample();

    // Tracked subset recipe: 95 printable ASCII + U+25A1 + 108 audited
    // non-ASCII sample scalars. Keep this independent of the input text.
    assert_eq!(pack.glyph_count(), 204);
    assert_eq!(pack.pixel_size(), PX);
    assert_eq!(pack.fallback_cp(), 0x25A1);

    let mut buf = vec![0u8; pack.max_glyph_len()];
    for ch in text.chars().filter(|c| *c != '\n' && !is_hangul(*c)) {
        let (res, bits) = pack.lookup(&mut r, ch, &mut buf).unwrap();
        assert!(!res.fallback, "{ch:?} is in the subset");
        assert_eq!(res.glyph.code_point, ch as u32);
        if ch != ' ' {
            assert!(bits.iter().any(|&b| b != 0), "{ch:?} has ink");
        }
    }

    // 閱 U+95B1: present, drawn with its own record
    let (res, _) = pack.lookup(&mut r, '閱', &mut buf).unwrap();
    assert!(!res.fallback);
    assert_eq!(res.glyph.code_point, 0x95B1);

    // 한 U+D55C: absent, laid out and drawn as the visible fallback □
    let (res, bits) = pack.lookup(&mut r, '한', &mut buf).unwrap();
    assert!(res.fallback);
    assert_eq!(res.glyph.code_point, 0x25A1);
    assert!(bits.iter().any(|&b| b != 0), "fallback has ink");
}

// one page: its byte range in the text and its lines (spans index `page`)
struct Page {
    start: usize,
    len: usize,
    lines: Vec<LineSpan>,
}

fn paginate(pack: &FontPack, r: &mut TestReader, text: &[u8]) -> Vec<Page> {
    let params = WrapParams {
        markup: MARKUP,
        max_lines: MAX_LINES,
        max_width_px: MAX_WIDTH,
        indent_px: 0,
        img_heights: &[],
        default_img_h: 0,
    };
    let mut pages = Vec::new();
    let mut start = 0;
    while start < text.len() {
        let mut lines = vec![LineSpan::EMPTY; MAX_LINES];
        let out = wrap(
            &text[start..],
            true,
            &mut PackMeasure::new(pack, r),
            &params,
            &mut lines,
        )
        .unwrap();
        assert!(out.consumed > 0, "page at byte {start} makes progress");
        lines.truncate(out.line_count);
        pages.push(Page {
            start,
            len: out.consumed,
            lines,
        });
        start += out.consumed;
    }
    pages
}

fn line_chars(page: &[u8], span: &LineSpan) -> Vec<char> {
    line_glyphs(page, span, MARKUP).map(|(ch, _)| ch).collect()
}

#[test]
fn real_font_keeps_cjk_after_an_underfilled_8192_byte_chunk() {
    let (mut reader, pack) = load();
    let mut text = vec![b'\r'; 8190];
    text.extend_from_slice("a中，字".as_bytes());
    let params = WrapParams {
        markup: MARKUP,
        max_lines: 37,
        max_width_px: MAX_WIDTH,
        indent_px: 0,
        img_heights: &[],
        default_img_h: 0,
    };

    let mut starts = Vec::new();
    let mut drawn = String::new();
    let mut start = 0;
    let mut state = WrapState::default();
    let mut rendered_pages = 0;
    while start < text.len() {
        starts.push(start);
        let end = (start + 8192).min(text.len());
        let mut lines = [LineSpan::EMPTY; 37];
        let out = wrap_stream(
            &text[start..end],
            end == text.len(),
            &mut PackMeasure::new(&pack, &mut reader),
            &params,
            &mut lines,
            state,
        )
        .unwrap();
        rendered_pages += usize::from(out.line_count > 0);
        for span in &lines[..out.line_count] {
            drawn.extend(line_chars(&text[start..end], span));
        }
        start = next_page_offset(start, out.consumed, text.len())
            .expect("page makes progress")
            .unwrap_or(text.len());
        state = out.next_state;
    }

    assert_eq!(starts, [0, 8190]);
    assert_eq!(rendered_pages, 1);
    assert_eq!(drawn, "a中，字");
}

#[test]
fn pagination_keeps_all_text_and_the_kinsoku_rules() {
    let (mut r, pack) = load();
    let text = sample();
    let bytes = text.as_bytes();
    let pages = paginate(&pack, &mut r, bytes);

    // 1 em = 24 px per ideograph, so ~10 per 240 px line: well over 6 lines
    assert!(pages.len() >= 2, "the sample spans pages: {}", pages.len());
    assert_eq!(
        pages.iter().map(|p| p.len).sum::<usize>(),
        bytes.len(),
        "pages cover the text"
    );

    let mut lines: Vec<Vec<char>> = Vec::new();
    for p in &pages {
        let page = &bytes[p.start..p.start + p.len];
        assert!(!p.lines.is_empty() && p.lines.len() <= MAX_LINES);
        for span in &p.lines {
            let chars = line_chars(page, span);
            // measured as layout measures it; a trailing space may overhang
            let mut m = PackMeasure::new(&pack, &mut r);
            let width: u32 = chars
                .iter()
                .rev()
                .skip_while(|c| **c == ' ')
                .map(|&c| m.advance(c, Style::Regular).unwrap())
                .sum();
            assert!(width <= MAX_WIDTH, "line {chars:?} is {width} px");
            lines.push(chars);
        }
    }

    // nothing omitted, nothing duplicated: the drawn scalars are the text's
    // scalars in order, apart from the spaces a line break may drop and the
    // newline that ends the paragraph
    let drawn: String = lines.iter().flatten().filter(|c| **c != ' ').collect();
    let want: String = text.chars().filter(|c| !c.is_whitespace()).collect();
    assert_eq!(drawn, want);

    for (i, line) in lines.iter().enumerate() {
        let s: String = line.iter().collect();
        let first = *line.first().expect("no empty text line in the sample");
        let last = *line.iter().rev().find(|c| **c != ' ').unwrap();
        assert!(
            !NO_LINE_START.contains(first),
            "line {i} starts with {first:?}: {s}"
        );
        assert!(
            !NO_LINE_END.contains(last),
            "line {i} ends with {last:?}: {s}"
        );
        if let Some(next) = lines.get(i + 1) {
            let next_first = next[0];
            assert!(
                !(last == next_first && NO_SPLIT_PAIRS.contains(last)),
                "{last}{last} split after line {i}: {s}"
            );
        }
    }
}

// logical (lx, ly) -> physical (ly, 479 - lx) under Deg270, so logical row
// band [y0, y0 + h) is physical columns [y0, y0 + h), all physical rows
fn band_ink(frame: &Frame, y0: i32, h: i32) -> usize {
    frame.black_pixels_in(y0 as u16, 0, h as u16, 480).len()
}

#[test]
fn every_page_draws_each_line_from_ram_alone() {
    let (mut r, pack) = load();
    let text = sample();
    let bytes = text.as_bytes();
    let pages = paginate(&pack, &mut r, bytes);
    let lh = pack.line_height() as i32;
    let geom = PageGeometry {
        left: LEFT,
        top: TOP,
        line_height: lh,
        ascent: pack.ascent() as i32,
        indent_px: 0,
    };

    for (n, p) in pages.iter().enumerate() {
        let page = &bytes[p.start..p.start + p.len];
        let mut cache: Box<PageGlyphs<96, 8192>> = Box::new(PageGlyphs::new());
        cache
            .prepare(&pack, &mut r, page, &p.lines, MARKUP)
            .unwrap_or_else(|e| panic!("page {n}: {e:?}"));

        let (reads, bytes_read) = (r.reads, r.bytes_read);
        let frame = render_full(Rotation::Deg270, &|s: &mut StripBuffer| {
            cache.draw(s, page, &p.lines, MARKUP, &geom).unwrap();
        });
        assert_eq!(
            (r.reads, r.bytes_read),
            (reads, bytes_read),
            "page {n}: drawing read the font"
        );

        // every text line puts ink in its own line band
        for row in 0..p.lines.len() as i32 {
            assert!(
                band_ink(&frame, TOP + row * lh, lh) > 0,
                "page {n} line {row}: no ink (see {})",
                frame.write_pbm(&format!("iansui-page{n}")).display()
            );
        }
        // and nothing lands outside the page's text block: above the first
        // line, below the last, or past the line width plus one em of
        // overhang (logical x = 479 - physical y)
        let block_end = TOP + p.lines.len() as i32 * lh;
        for (px, py) in frame.black_pixels() {
            let (lx, ly) = (479 - py as i32, px as i32);
            assert!(
                (TOP..block_end).contains(&ly) && lx < LEFT + MAX_WIDTH as i32 + PX as i32,
                "page {n}: stray ink at logical ({lx},{ly}) (see {})",
                frame.write_pbm(&format!("iansui-page{n}")).display()
            );
        }
    }
}
