// Distributable English fixtures for the reader regressions (English reader regression): plain-text
// files and EPUB 2 / EPUB 3 books generated from a spec. Everything here is a
// pure function of its arguments -- no clock, no randomness, no I/O -- so the
// same spec always yields the same bytes. The content is synthetic (written
// for the fixtures, see `standard`); the EPUBs declare it in dc:rights.
//
// Only the writers live here. Reading the books back is the job of the
// production smol-epub parsers and decoders that the tests run.

mod image;
mod markup;
mod standard;
mod zip;

use smol_epub::epub::{AUTHOR_CAP, TITLE_CAP, TOC_TITLE_CAP};

pub use standard::{Fixture, Spec, standard, standard_card};

pub(crate) const RIGHTS: &str =
    "Synthetic test fixture generated by pulp-os; contains no third-party text.";
// fixed dcterms:modified of every EPUB 3 package
pub(crate) const MODIFIED: &str = "2000-01-01T00:00:00Z";

// ---- TXT ------------------------------------------------------------------

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Newline {
    Lf,
    CrLf,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TxtSpec {
    // logical lines without '\r' / '\n'; "" is a blank line
    pub lines: Vec<String>,
    pub newline: Newline,
    pub trailing_newline: bool,
}

pub fn build_txt(spec: &TxtSpec) -> Vec<u8> {
    if spec.lines.is_empty() {
        return Vec::new();
    }
    let eol = match spec.newline {
        Newline::Lf => "\n",
        Newline::CrLf => "\r\n",
    };
    let mut text = spec.lines.join(eol);
    if spec.trailing_newline {
        text.push_str(eol);
    }
    text.into_bytes()
}

// ---- EPUB -----------------------------------------------------------------

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EpubVersion {
    V2,
    V3,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Compression {
    Stored,
    Deflate,
    Mixed,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Run {
    Text(String),
    Bold(String),
    Italic(String),
    Break,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Block {
    Paragraph(Vec<Run>),
    Heading(String),
    // index into EpubSpec::images
    Image(usize),
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Chapter {
    pub title: String,
    pub blocks: Vec<Block>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TocItem {
    pub title: String,
    // index into EpubSpec::chapters
    pub chapter: usize,
    pub children: Vec<TocItem>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Pattern {
    Black,
    White,
    // pixel (x, y) is black iff (x / cell + y / cell) is even
    Checker { cell: u16 },
    // PNG: luminance x * 255 / (w - 1); JPEG: the same per 8x8 block
    HorizontalGradient,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ImageKind {
    PngGray1,
    PngGray8,
    PngPalette8,
    Jpeg,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ImageSpec {
    // relative to "OEBPS/", e.g. "images/cover.png"
    pub path: String,
    pub kind: ImageKind,
    pub width: u16,
    pub height: u16,
    pub pattern: Pattern,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EpubSpec {
    pub version: EpubVersion,
    pub title: String,
    pub author: String,
    pub identifier: String,
    // spine order == chapter order
    pub chapters: Vec<Chapter>,
    // nested; the production parsers flatten it pre-order
    pub toc: Vec<TocItem>,
    pub images: Vec<ImageSpec>,
    // index into `images`
    pub cover: Option<usize>,
    pub compression: Compression,
    // write every non-ASCII character of the chapter XHTML as &#N;
    pub numeric_entities: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SpecError {
    NoChapters,
    EmptyChapter(usize),
    // the offending chapter index
    BadTocTarget(usize),
    BadImage(usize),
    // the offending image index
    BadImageRef(usize),
    TitleTooLong,
}

fn image_is_valid(im: &ImageSpec) -> bool {
    if im.width == 0 || im.height == 0 {
        return false;
    }
    match (im.kind, im.pattern) {
        (_, Pattern::Checker { cell: 0 }) => false,
        (ImageKind::PngGray1 | ImageKind::PngPalette8, Pattern::HorizontalGradient) => false,
        (ImageKind::Jpeg, pattern) => {
            im.width % 8 == 0
                && im.height % 8 == 0
                && !matches!(pattern, Pattern::Checker { cell } if cell % 8 != 0)
        }
        _ => true,
    }
}

fn check_toc(items: &[TocItem], chapters: usize) -> Result<(), SpecError> {
    for it in items {
        if it.chapter >= chapters {
            return Err(SpecError::BadTocTarget(it.chapter));
        }
        if it.title.len() > TOC_TITLE_CAP {
            return Err(SpecError::TitleTooLong);
        }
        check_toc(&it.children, chapters)?;
    }
    Ok(())
}

fn check(spec: &EpubSpec) -> Result<(), SpecError> {
    if spec.chapters.is_empty() {
        return Err(SpecError::NoChapters);
    }
    if let Some(i) = spec.chapters.iter().position(|c| c.blocks.is_empty()) {
        return Err(SpecError::EmptyChapter(i));
    }
    if spec.title.len() > TITLE_CAP || spec.author.len() > AUTHOR_CAP {
        return Err(SpecError::TitleTooLong);
    }
    check_toc(&spec.toc, spec.chapters.len())?;
    if let Some(i) = spec.images.iter().position(|im| !image_is_valid(im)) {
        return Err(SpecError::BadImage(i));
    }
    let referenced = spec
        .chapters
        .iter()
        .flat_map(|c| &c.blocks)
        .filter_map(|b| match b {
            Block::Image(i) => Some(*i),
            _ => None,
        })
        .chain(spec.cover);
    for i in referenced {
        if i >= spec.images.len() {
            return Err(SpecError::BadImageRef(i));
        }
    }
    Ok(())
}

// entry `i` (0 is mimetype, always stored) is deflated under `c`
fn is_deflated(c: Compression, i: usize) -> bool {
    match c {
        Compression::Stored => false,
        Compression::Deflate => i != 0,
        Compression::Mixed => i % 2 == 1,
    }
}

pub fn build_epub(spec: &EpubSpec) -> Result<Vec<u8>, SpecError> {
    check(spec)?;

    let toc = match spec.version {
        EpubVersion::V2 => ("OEBPS/toc.ncx", markup::ncx(spec)),
        EpubVersion::V3 => ("OEBPS/nav.xhtml", markup::nav(spec)),
    };
    let mut parts: Vec<(String, Vec<u8>)> = vec![
        ("mimetype".into(), b"application/epub+zip".to_vec()),
        (
            "META-INF/container.xml".into(),
            markup::container().into_bytes(),
        ),
        ("OEBPS/content.opf".into(), markup::opf(spec).into_bytes()),
        (toc.0.into(), toc.1.into_bytes()),
    ];
    for (i, ch) in spec.chapters.iter().enumerate() {
        parts.push((
            format!("OEBPS/{}", markup::chapter_href(i)),
            markup::chapter(spec, ch).into_bytes(),
        ));
    }
    for im in &spec.images {
        parts.push((format!("OEBPS/{}", im.path), image::encode(im)));
    }

    let entries: Vec<zip::Entry> = parts
        .into_iter()
        .enumerate()
        .map(|(i, (name, data))| zip::Entry {
            name,
            data,
            deflate: is_deflated(spec.compression, i),
        })
        .collect();
    Ok(zip::write(&entries))
}
